var Router = require('router');
var router = Router();
var autenticacao = require('./autenticacao.js');
var usuario = require('./usuario.js');
var solicitacao = require('./solicitacao.js');
var deviceToken = require('./deviceToken.js');
var notificacao = require('./notificacao.js');
var localizacao = require('./localizacao.js');
var email = require('../utils/emailService.js');

router.post('/autenticacao/login', autenticacao.login);
router.post('/autenticacao/registrar', autenticacao.registrar);
router.post('/autenticacao/resetPassword', autenticacao.resetPassword);
router.get('/solicitacao/obterPorId/:id', solicitacao.obterPorId);
router.post('/solicitacao/solicitar', solicitacao.solicitar);
router.post('/solicitacao/editar', solicitacao.editar);
router.get('/solicitacao/obterTodas', solicitacao.obterTodas);
router.get('/solicitacao/obterSolicitacoesAtivasExcetoUltimaSolicitacaoPorUsuarioId/:id', solicitacao.obterSolicitacoesAtivasExcetoUltimaSolicitacaoPorUsuarioId);
router.post('/solicitacao/obterSolicitacoesAtivasExcetoUltimaSolicitacaoPorCategoriaId', solicitacao.obterSolicitacoesAtivasExcetoUltimaSolicitacaoPorCategoriaId);
router.get('/solicitacao/obterSolicitacoesPorCategoriaId/:id', solicitacao.obterSolicitacoesPorCategoriaId);
router.post('/solicitacao/obterListaSolicitacoesPorCategoriaId', solicitacao.obterListaSolicitacoesPorCategoriaId);
router.get('/solicitacao/obterSolicitacoesPorUsuarioId/:id', solicitacao.obterSolicitacoesPorUsuarioId);
router.get('/solicitacao/obterSolicitacoesIdPorUsuarioId/:id', solicitacao.obterSolicitacoesIdPorUsuarioId);
router.post('/solicitacao/obterSolicitacoesPorUsuarioECategoria', solicitacao.obterSolicitacoesPorUsuarioECategoria);
router.get('/usuario/obterFornecedoresPorCategoriaId/:id', usuario.obterFornecedoresPorCategoriaId);
router.get('/usuario/obterPorId/:id', usuario.obterPorId);
router.get('/usuario/obterTodos', usuario.obterTodos);
router.get('/usuario/obterTodosEstabelecimentos', usuario.obterTodosEstabelecimentos);
router.post('/usuario/adicionarCategoria', usuario.adicionarCategoria);
router.post('/usuario/removerCategoria', usuario.removerCategoria);
router.post('/usuario/obterListaUsuariosPorId', usuario.obterListaUsuariosPorId);
router.post('/usuario/remover/:id', usuario.remover);
router.post('/usuario/editar', usuario.editar);
router.post('/usuario/adicionar', usuario.adicionar);
router.get('/localizacao/obterCep/:cep', localizacao.obterCep);
router.get('/deviceToken/obterPorUsuarioId/:id', deviceToken.obterPorUsuarioId);
router.get('/deviceToken/obterPorId/:id', deviceToken.obterPorId);
router.post('/deviceToken/register', deviceToken.register);
router.post('/deviceToken/editar', deviceToken.editar);
router.post('/deviceToken/notificar', deviceToken.notificar);
router.post('/deviceToken/notificarUsuarios', deviceToken.notificarUsuarios);
router.post('/email/enviar', email.enviar);
router.post('/notificacao/adicionar', notificacao.adicionar);
router.get('/notificacao/obterPorUsuarioId/:id', notificacao.obterPorUsuarioId);
router.get('/notificacao/obterNotificacoesEmAbertoPorUsuarioId/:id', notificacao.obterNotificacoesEmAbertoPorUsuarioId);
router.get('/notificacao/editarListaPorUsuarioId/:id', notificacao.editarListaPorUsuarioId);

module.exports = router;
